export const CHANGE_CANVAS_SIZE = 'CHANGE_CANVAS_SIZE';
export const SET_CANVAS = 'SET_CANVAS';
export const SET_TOOL_MANAGER = 'SET_TOOL_MANAGER';

//
export const CHANGE_BRUSH_SETTING = 'CHANGE_BRUSH_SETTING';
export const SAVE_BRUSH = 'SAVE_BRUSH';
export const CHANGE_CANVAS_DEFAULT_BACKGROUND = 'CHANGE_CANVAS_DEFAULT_BACKGROUND';
export const CHANGE_SAVED_BRUSHES = 'CHANGE_SAVED_BRUSHES';

//
export const CHANGE_LAYOUT_LIST = 'CHANGE_LAYOUT_LIST';
export const CHANGE_CURRENT_LAYOUT = 'CHANGE_CURRENT_LAYOUT';
export const ADD_LAYOUT_MANAGER = 'ADD_LAYOUT_MANAGER';

