export const CHANGE_CANVAS_SIZE = 'CHANGE_CANVAS_SIZE';
export const SET_CANVAS = 'SET_CANVAS';
export const SET_CURRENT_TOOL = 'CHANGE_CURRENT_TOOL';
export const SET_CANVAS_BLOCK = 'SET_CANVAS_BLOCK';
export const SET_CANVAS_POSITION = 'SET_CANVAS_POSITION';
export const SET_CANVAS_ZOOM = 'SET_CANVAS_ZOOM';
//
export const CHANGE_BRUSH_SETTING = 'CHANGE_BRUSH_SETTING';
export const SAVE_BRUSH = 'SAVE_BRUSH';
export const CHANGE_CANVAS_DEFAULT_BACKGROUND = 'CHANGE_CANVAS_DEFAULT_BACKGROUND';
export const CHANGE_SAVED_BRUSHES = 'CHANGE_SAVED_BRUSHES';
export const CHANGE_ACTIVE_TOOL = 'CHANGE_ACTIVE_TOOL';

//
export const CHANGE_LAYOUT_LIST = 'CHANGE_LAYOUT_LIST';
export const CHANGE_CURRENT_LAYOUT = 'CHANGE_CURRENT_LAYOUT';
export const ADD_LAYOUT_MANAGER = 'ADD_LAYOUT_MANAGER';

//
export const CHANGE_FRAME_LIST = 'CHANGE_FRAME_LIST';
export const SET_MULTIPLICATE_CANVAS = 'SET_MULTIPLICATE_CANVAS';
export const STOP_PLAY = 'STOP_PLAY';
export const CAN_PLAY = 'CAN_PLAY';
export const SET_CURRENT_FRAME = 'SET_CURRENT_FRAME';

//
export const IMAGE_TOOL_SET_FILE = 'IMAGE_TOOL_SET_FILE';
export const IMAGE_TOOL_DRAG_BLOCK_ENABLE = 'IMAGE_TOOL_DRAG_BLOCK_ENABLE';
export const IMAGE_TOOL_DRAG_BLOCK_DISABLE = 'IMAGE_TOOL_DRAG_BLOCK_DISABLE';
export const IMAGE_TOOL_SET_POSITION = 'IMAGE_TOOL_SET_POSITION';
export const IMAGE_TOOL_ACCEPT_CHANGES = 'IMAGE_TOOL_ACCEPT_CHANGES'
export const IMAGE_TOOL_FINISH = 'IMAGE_TOOL_FINISH';
//
